package com.flying.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.flying.famous.quotes.db.Like;
import com.flying.famous.quotes.db.Quotes;
import com.flying.famous.quotes.db.Type;

import com.flying.greendao.db.LikeDao;
import com.flying.greendao.db.QuotesDao;
import com.flying.greendao.db.TypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likeDaoConfig;
    private final DaoConfig quotesDaoConfig;
    private final DaoConfig typeDaoConfig;

    private final LikeDao likeDao;
    private final QuotesDao quotesDao;
    private final TypeDao typeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likeDaoConfig = daoConfigMap.get(LikeDao.class).clone();
        likeDaoConfig.initIdentityScope(type);

        quotesDaoConfig = daoConfigMap.get(QuotesDao.class).clone();
        quotesDaoConfig.initIdentityScope(type);

        typeDaoConfig = daoConfigMap.get(TypeDao.class).clone();
        typeDaoConfig.initIdentityScope(type);

        likeDao = new LikeDao(likeDaoConfig, this);
        quotesDao = new QuotesDao(quotesDaoConfig, this);
        typeDao = new TypeDao(typeDaoConfig, this);

        registerDao(Like.class, likeDao);
        registerDao(Quotes.class, quotesDao);
        registerDao(Type.class, typeDao);
    }
    
    public void clear() {
        likeDaoConfig.clearIdentityScope();
        quotesDaoConfig.clearIdentityScope();
        typeDaoConfig.clearIdentityScope();
    }

    public LikeDao getLikeDao() {
        return likeDao;
    }

    public QuotesDao getQuotesDao() {
        return quotesDao;
    }

    public TypeDao getTypeDao() {
        return typeDao;
    }

}
